-- MySQL Script generated by MySQL Workbench
-- mar 21 nov 2017 20:58:45 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `botanica` ;

-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `botanica` DEFAULT CHARACTER SET utf8 ;
USE `botanica` ;

-- -----------------------------------------------------
-- Table `botanica`.`climas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`climas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`climas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`estados` ;

CREATE TABLE IF NOT EXISTS `botanica`.`estados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`roles` ;

CREATE TABLE IF NOT EXISTS `botanica`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(50) NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `botanica`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `user` VARCHAR(16) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NULL,
  `roles_id` INT(50) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_rol`
    FOREIGN KEY (`roles_id`)
    REFERENCES `botanica`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE UNIQUE INDEX `user_UNIQUE` ON `botanica`.`usuarios` (`user` ASC);

CREATE UNIQUE INDEX `roles_id_UNIQUE` ON `botanica`.`usuarios` (`roles_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`suelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`suelos` ;

CREATE TABLE IF NOT EXISTS `botanica`.`suelos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`temporadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`temporadas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`temporadas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`tipos_plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`tipos_plantas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`tipos_plantas` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`plantas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`plantas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `suelos_id` INT(11) NOT NULL,
  `climas_id` INT(11) NOT NULL,
  `temporadas_id` INT(11) NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `tiempo_riego` DATETIME NULL,
  `tipo_planta_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_plantas_clima`
    FOREIGN KEY (`climas_id`)
    REFERENCES `botanica`.`climas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_suelos`
    FOREIGN KEY (`suelos_id`)
    REFERENCES `botanica`.`suelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_tempo`
    FOREIGN KEY (`temporadas_id`)
    REFERENCES `botanica`.`temporadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_tiposPl`
    FOREIGN KEY (`tipo_planta_id`)
    REFERENCES `botanica`.`tipos_plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_plantas_clima_idx` ON `botanica`.`plantas` (`climas_id` ASC);

CREATE INDEX `fk_plantas_suelos_idx` ON `botanica`.`plantas` (`suelos_id` ASC);

CREATE INDEX `fk_plantas_tempo_idx` ON `botanica`.`plantas` (`temporadas_id` ASC);

CREATE INDEX `fk_plantas_tiposPl_idx` ON `botanica`.`plantas` (`tipo_planta_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`seguimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`seguimientos` ;

CREATE TABLE IF NOT EXISTS `botanica`.`seguimientos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `planta_id` INT(11) NOT NULL,
  `estado_id` INT(11) NOT NULL,
  `ultimo_riego` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_seguim_user`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `botanica`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguim_planta`
    FOREIGN KEY (`planta_id`)
    REFERENCES `botanica`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguim_estados`
    FOREIGN KEY (`estado_id`)
    REFERENCES `botanica`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_seguim_user_idx` ON `botanica`.`seguimientos` (`usuario_id` ASC);

CREATE INDEX `fk_seguim_planta_idx` ON `botanica`.`seguimientos` (`planta_id` ASC);

CREATE INDEX `fk_seguim_estados_idx` ON `botanica`.`seguimientos` (`estado_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`etapas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`etapas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(512) NULL,
  `seguimiento_id` INT(11) NULL,
  `planta_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_etapas_seguim`
    FOREIGN KEY (`seguimiento_id`)
    REFERENCES `botanica`.`seguimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etapas_planta`
    FOREIGN KEY (`planta_id`)
    REFERENCES `botanica`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_etapas_seguim_idx` ON `botanica`.`etapas` (`seguimiento_id` ASC);

CREATE INDEX `fk_etapas_planta_idx` ON `botanica`.`etapas` (`planta_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`personas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`personas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personas_user`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `botanica`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_personas_user_idx` ON `botanica`.`personas` (`usuarios_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`categorias` ;

CREATE TABLE IF NOT EXISTS `botanica`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`temas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`temas` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `cerrado` TINYINT(1) NULL DEFAULT NULL,
  `texto` VARCHAR(256) NULL DEFAULT NULL,
  `categoria_id` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_preguntas_categ`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `botanica`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preguntas_user`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `botanica`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_preguntas_temas_idx` ON `botanica`.`temas` (`categoria_id` ASC);

CREATE INDEX `fk_preguntas_user_idx` ON `botanica`.`temas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`respuestas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`respuestas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `temas_id` INT(11) NULL,
  `texto` VARCHAR(255) NULL,
  `usuario_id` INT(11) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_respuestas_preg`
    FOREIGN KEY (`temas_id`)
    REFERENCES `botanica`.`temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuestas_user`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `botanica`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_respuestas_preg_idx` ON `botanica`.`respuestas` (`temas_id` ASC);

CREATE INDEX `fk_respuestas_user_idx` ON `botanica`.`respuestas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`tareas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`tareas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `etapas_id` INT(11) NOT NULL,
  `descripcion` VARCHAR(512) NOT NULL,
  `estados_id` INT(11) NOT NULL,
  `plantas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tareas_etapas`
    FOREIGN KEY (`etapas_id`)
    REFERENCES `botanica`.`etapas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_estados`
    FOREIGN KEY (`estados_id`)
    REFERENCES `botanica`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_plantas`
    FOREIGN KEY (`plantas_id`)
    REFERENCES `botanica`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tareas_etapas_idx` ON `botanica`.`tareas` (`etapas_id` ASC);

CREATE INDEX `fk_tareas_estados_idx` ON `botanica`.`tareas` (`estados_id` ASC);

CREATE INDEX `fk_tareas_plantas_idx` ON `botanica`.`tareas` (`plantas_id` ASC);


-- -----------------------------------------------------
-- Table `botanica`.`tipos_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`tipos_ventas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`tipos_ventas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `botanica`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botanica`.`ventas` ;

CREATE TABLE IF NOT EXISTS `botanica`.`ventas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `usuarios_id` INT(11) NULL,
  `cerrado` TINYINT(1) NULL,
  `fecha` DATETIME NULL,
  `tipo_venta_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ventas_tipos`
    FOREIGN KEY (`tipo_venta_id`)
    REFERENCES `botanica`.`tipos_ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_user`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `botanica`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_ventas_tipos_idx` ON `botanica`.`ventas` (`tipo_venta_id` ASC);

CREATE INDEX `fk_ventas_user_idx` ON `botanica`.`ventas` (`usuarios_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `botanica`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `botanica`;
INSERT INTO `botanica`.`roles` (`id`, `rol`, `descripcion`) VALUES (1, 'ROLE_ADMIN', 'Administrador');
INSERT INTO `botanica`.`roles` (`id`, `rol`, `descripcion`) VALUES (2, 'ROLE_USER', 'Usuario Comun');
INSERT INTO `botanica`.`roles` (`id`, `rol`, `descripcion`) VALUES (3, 'ROLE_VENDEDOR', 'Usuario Vendedor');

COMMIT;

