-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 19:24:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `botanica` ;

-- -----------------------------------------------------
-- Schema botanica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `botanica` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `botanica` ;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` INT(50) NULL,
  `descripcion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `user` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `roles_id` INT(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_UNIQUE` ON `usuarios` (`user` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `roles_id_UNIQUE` ON `usuarios` (`roles_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `edad` INT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `temas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `temas` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preguntas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `preguntas` (
  `id` INT NOT NULL ,
  `titulo` VARCHAR(45) NULL,
  `usuario_id` INT NULL,
  `cerrado` TINYINT NULL,
  `texto` TEXT(255) NULL,
  `temas_id` INT NULL ,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `usuarios_id_UNIQUE` ON `preguntas` (`usuario_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `temas_id_UNIQUE` ON `preguntas` (`temas_id` ASC);

SHOW WARNINGS;


-- -----------------------------------------------------
-- Table `respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `respuestas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preguntas_id` INT NULL,
  `texto` VARCHAR(255) NULL,
  `usuario_id` INT NULL,
  `respuestascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `respuestas` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `preguntas_id_UNIQUE` ON `respuestas` (`preguntas_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `usuario_id_UNIQUE` ON `respuestas` (`usuario_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `climas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `climas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `climas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `suelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `suelos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `suelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `temporadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temporadas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `temporadas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tiposPlantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiposPlantas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tiposPlantas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '			';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `plantas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plantas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `plantas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `suelo_id` INT NULL,
  `clima_id` INT NULL,
  `temporada_id` INT NULL,
  `descripcion` VARCHAR(512) NULL,
  `tiempoRiego` DATETIME NULL,
  `tiposPlantas_id` INT NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `plantas` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(512) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `estados` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etapas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `etapas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(512) NULL DEFAULT CURRENT_TIMESTAMP,
  `seguimiento_id` INT NULL,
  `planta_id` INT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `seguimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguimientos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `seguimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `planta_id` INT NOT NULL,
  `estado_id` INT NULL,
  `ultimoRiego` DATETIME NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `etapas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etapas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `etapas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(512) NULL,
  `seguimiento_id` INT NULL,
  `planta_id` INT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tiposVentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tiposVentas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tiposVentas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL,
  `dscripcion` VARCHAR(255) NOT NULL,
  `usuarios_id` INT NULL,
  `cerrado` TINYINT(1) NULL,
  `fecha` DATETIME NULL,
  `tiposVentas_id` INT NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tareas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `etapa_id` INT NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `estado` INT NULL,
  `planta_id` INT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
